name:                zlib-core
version:             0.1.0.1
github:              "YoshikuniJujo/zlib-core"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "(c) 2025 Yoshikuni Jujo"

extra-source-files:
- README.md

extra-doc-files:
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Thin wrapper for zlib
category:            Codec

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/zlib-core#readme>

dependencies:
- base >= 4.7 && < 5
- primitive >= 0.9 && < 0.10
- c-enum >= 0.1 && < 0.2
- c-struct >= 0.1 && < 0.2
- exception-hierarchy >= 0.1 && < 0.2
- tools-yj >= 0.1 && < 0.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  pkg-config-dependencies:
    - zlib

tests:
  zlib-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zlib-core
